version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm dependencies"
      - "triage-board"
    target-branch: "dependabot-staging"
