[build]
  command = "VITE_COMMIT_REF=$COMMIT_REF yarn build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  command = "yarn dev"
  port = 5174
  [dev.env]
    URL = "http://localhost:5174"

[build.environment]
  FONTCONFIG_PATH = "./netlify/functions/fonts"
  FC_LANG = "en_US.UTF-8"
  
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[[redirects]]
  # This rule proxies requests from a clean API path to your function
  from = "/api/convert/*"
  to = "/.netlify/functions/convert/:splat"
  status = 200