// netlify/functions/mcp/types.ts
// AUTOGENERATED FROM http://blpy.attilafarago.hu/swagger.json

export interface ModelContextRequest {
  modelId: string;
  revisionId?: string;
}

export interface ModelContextResponse {
  contextId: string;
  modelId: string;
  revisionId: string;
  parameters: Record<string, unknown>;
}

export interface ModelChangeRequest {
  contextId: string;
  changes: Array<{
    path: string;
    op: 'add' | 'replace' | 'remove';
    value?: unknown;
  }>;
}

export interface ModelChangeResponse {
  contextId: string;
  updated: boolean;
  errors?: Array<{ path: string; message: string }>; 
}