name: Build and Deploy to Github-Pages

on:
    workflow_dispatch: # Allows you to run this workflow manually
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Create version file
              run: |
                  echo "const GITHUB_VERSION = '${GITHUB_SHA:0:7} ${GITHUB_REF_NAME}'; export { GITHUB_VERSION };" > ./src/github_version.ts

            - name: Build
              run: |
                  npm install
                  npm build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: 'build/.'

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: 'https://blpy.attilafarago.hu/'
        steps:
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Deploy
              uses: actions/deploy-pages@v4
